name: Build Livo APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: إعداد Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable

      - name: إنشاء ملفات Android
        run: |
          flutter create --platforms=android temp_livo
          cp -r temp_livo/android .
          cp temp_livo/.metadata .
          cp temp_livo/analysis_options.yaml .

      - name: تثبيت الحزم
        run: flutter pub get

      - name: بناء APK
        run: flutter build apk --release

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: Livo-APK
          path: build/app/outputs/flutter-apk/app-release.apk
